
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktwcyzsxzivlibsaschj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0d2N5enN4eml2bGlic2FzY2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzY4NTAsImV4cCI6MjA2MjgxMjg1MH0.upfigrj13S8wW_C-nIxYbrzBrOyMitEN-wcDVCzJ7zY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create Supabase client with proper authentication configuration
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      detectSessionInUrl: true
    },
    global: {
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY,
        'Content-Type': 'application/json'
      },
      // Custom fetch handler with improved logging and retry logic
      fetch: (url, options = {}) => {
        // Ensure headers are properly passed and structured
        const fetchOptions = {
          ...options,
          headers: {
            ...((options as any)?.headers || {}),
            'apikey': SUPABASE_PUBLISHABLE_KEY,
            'Content-Type': 'application/json'
          }
        };
        
        // Log fetch details for debugging
        console.log('Supabase fetch URL:', url);
        console.log('Fetch options:', JSON.stringify({
          ...fetchOptions,
          headers: {
            ...((fetchOptions as any).headers || {}),
            // Mask sensitive data in logs
            Authorization: (fetchOptions as any).headers?.Authorization ? 'Bearer token present' : 'No auth token'
          }
        }, null, 2));
        
        // Implement retry logic for network issues
        let retries = 0;
        const maxRetries = 3;
        const baseDelay = 500;
        
        const executeFetch = async (): Promise<Response> => {
          try {
            // Add session token to request if available but not already present
            if (typeof localStorage !== 'undefined' && !(fetchOptions as any)?.headers?.Authorization) {
              try {
                const session = JSON.parse(localStorage.getItem('supabase.auth.token') || '{}');
                if (session?.access_token) {
                  (fetchOptions as any).headers.Authorization = `Bearer ${session.access_token}`;
                  console.log('Added auth token to request from localStorage');
                }
              } catch (err) {
                console.warn('Failed to get session from localStorage:', err);
              }
            }
            
            const response = await fetch(url, fetchOptions);
            
            // Log response status and details for debugging
            console.log(`Response status for ${url}: ${response.status}`);
            if (response.status >= 400) {
              try {
                const errorText = await response.clone().text();
                console.error(`Error response for ${url}:`, response.statusText, errorText);
              } catch (error) {
                console.error(`Error capturing error details for ${url}:`, error);
              }
            }
            return response;
          } catch (error) {
            console.error(`Fetch error for ${url}:`, error);
            if (retries < maxRetries) {
              retries++;
              const delay = baseDelay * Math.pow(2, retries - 1); // Exponential backoff
              console.log(`Retrying in ${delay}ms (attempt ${retries} of ${maxRetries})...`);
              await new Promise(resolve => setTimeout(resolve, delay));
              return executeFetch();
            }
            throw error;
          }
        };
        
        return executeFetch();
      }
    }
  }
);

// More robust session validation that doesn't throw errors
export const hasValidSession = async (): Promise<boolean> => {
  try {
    // First check localStorage for a token to avoid unnecessary network requests
    if (typeof localStorage !== 'undefined') {
      try {
        const sessionStr = localStorage.getItem('supabase.auth.token');
        if (!sessionStr) {
          console.log("No session found in localStorage");
          return false;
        }
        
        const sessionData = JSON.parse(sessionStr);
        if (!sessionData?.access_token) {
          console.log("No access token in localStorage session");
          return false;
        }
        
        // Check if token is expired
        const expiresAt = sessionData?.expires_at;
        if (expiresAt && expiresAt < Math.floor(Date.now() / 1000)) {
          console.log("Session token is expired");
          return false;
        }
      } catch (e) {
        console.warn("Error checking localStorage session:", e);
      }
    }
    
    // Double-check with the server
    const { data, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error("Session validation error:", error);
      return false;
    }
    
    const isValid = !!data.session?.user && !!data.session?.access_token;
    console.log("Session validation result:", isValid ? "Valid session" : "No valid session");
    return isValid;
  } catch (e) {
    console.error("Failed to validate session:", e);
    return false;
  }
};

// Enhanced logging of authentication state
export const logAuthState = async () => {
  try {
    const { data: { session } } = await supabase.auth.getSession();
    
    if (session) {
      const expiresAt = session.expires_at 
        ? new Date(session.expires_at * 1000).toISOString() 
        : 'unknown';
      
      console.log("Auth state:", {
        isAuthenticated: true,
        user: {
          id: session.user.id,
          email: session.user.email,
          has_access_token: !!session.access_token
        },
        expires_at: expiresAt,
        current_time: new Date().toISOString()
      });
      
      // Verify token is in localStorage
      if (typeof localStorage !== 'undefined') {
        try {
          const localSession = localStorage.getItem('supabase.auth.token');
          console.log("LocalStorage session exists:", !!localSession);
        } catch (e) {
          console.warn("Error checking localStorage:", e);
        }
      }
      
      return true;
    } else {
      console.log("Auth state: No active session");
      return false;
    }
  } catch (e) {
    console.error("Failed to log auth state:", e);
    return false;
  }
};
