
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktwcyzsxzivlibsaschj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0d2N5enN4eml2bGlic2FzY2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzY4NTAsImV4cCI6MjA2MjgxMjg1MH0.upfigrj13S8wW_C-nIxYbrzBrOyMitEN-wcDVCzJ7zY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      storage: localStorage
    },
    global: {
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY,
        'Content-Type': 'application/json'
      },
      fetch: (url, options = {}) => {
        const fetchOptions = {
          ...options,
          headers: {
            ...((options as any)?.headers || {}),
            'apikey': SUPABASE_PUBLISHABLE_KEY,
            'Content-Type': 'application/json'
          }
        };
        
        console.log('Supabase fetch URL:', url);
        console.log('Fetch options:', JSON.stringify(fetchOptions, null, 2));
        
        return fetch(url, fetchOptions)
          .then(response => {
            console.log(`Response status for ${url}: ${response.status}`);
            return response;
          })
          .catch(error => {
            console.error(`Fetch error for ${url}:`, error);
            throw error;
          });
      }
    }
  }
);
